sonar.projectKey=taskmanager
sonar.host.url=http://localhost:9000
sonar.login=${SONAR_TOKEN}

sonar.sources=backend/src
sonar.exclusions=node_modules/**

sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info