sonar.projectKey=taskmanager
sonar.host.url=http://localhost:9000
sonar.login=sqp_2b3667f48b9387ea1c5705447ffab32199f02f48

sonar.sources=backend/src
sonar.exclusions=node_modules/**

sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info
